{{- if .Values.aiSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aiSecret.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.aiSecret.data.OPENAI_API_KEY }}
  OPENAI_API_KEY: {{ . }}
  {{- end }}
  {{- with .Values.aiSecret.data.ANTHROPIC_API_KEY }}
  ANTHROPIC_API_KEY: {{ . }}
  {{- end }}
{{- end }}
